### PR TITLE
Return a default APIClient if we run into an exception

### LINKED ISSUE #1946: Create A Default Client In Spring Autoconfiguration
Currently if an `ApiClient` cannot be created when Spring AutoConfiguration is run the application will fail to start.  This is common when running an app with `client-java-spring-integration` on the classpath but maybe starting the app outside of Kubernetes.  In Spring Cloud Kubernetes we have done something like this.  
https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/spring-cloud-kubernetes-client-autoconfig/src/main/java/org/springframework/cloud/kubernetes/client/KubernetesClientUtils.java#L34

I wonder if we could maybe do the same thing in the auto configuration classes in the Kuberentes Java Client?

### PR DESCRIPTION
**Pull request by ryanjbaxter**
Fixes #1946

### CODE REVIEW

**Comment by ryanjbaxter** [comment]
I signed it

File: spring/src/main/java/io/kubernetes/client/spring/extended/controller/config/KubernetesInformerAutoConfiguration.java [hunk 1]
```diff
@@ -25,10 +28,32 @@
 @ConditionalOnKubernetesInformerEnabled
 public class KubernetesInformerAutoConfiguration {
 
+  private static final Log LOG = LogFactory.getLog(KubernetesInformerAutoConfiguration.class);
+
   @Bean
   @ConditionalOnMissingBean
   public ApiClient defaultApiClient() throws IOException {
-    return ClientBuilder.defaultClient();
+    try {
```
Comment (brendandburns) [inline spring/src/main/java/io/kubernetes/client/spring/extended/controller/config/KubernetesInformerAutoConfiguration.java:36]: The current [`defaultClient()`](https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/ClientBuilder.java#L103) tries to load from a local config in the following order:
* `$KUBECONFIG` if it exists
* `$HOME/.kube/config` if it exists
* in-cluster configuration if it exists
* localhost:8080 if all else fails

I think we should maintain that order of selection.

What are the specific exceptions that you are seeing? They're not listed in the issue.

I'd prefer we fixed the specific exceptions while maintaining the same load order.

Comment (brendandburns) [reply spring/src/main/java/io/kubernetes/client/spring/extended/controller/config/KubernetesInformerAutoConfiguration.java:36]: And perhaps it is better to add the exception handling to the `defaultClient()` function instead of the Spring loader.

File: spring/src/main/java/io/kubernetes/client/spring/extended/controller/config/KubernetesInformerAutoConfiguration.java [hunk 2]
```diff
@@ -25,10 +28,32 @@
 @ConditionalOnKubernetesInformerEnabled
 public class KubernetesInformerAutoConfiguration {
 
+  private static final Log LOG = LogFactory.getLog(KubernetesInformerAutoConfiguration.class);
```
Comment (yue9944882) [inline spring/src/main/java/io/kubernetes/client/spring/extended/controller/config/KubernetesInformerAutoConfiguration.java:31]: nit: conventionally we use slf4j as the logging interface

**Review by yue9944882 — COMMENTED** [review]
plz run `mvn spotless:apply` to fix the format error

**Comment by ryanjbaxter** [comment]
@yue9944882 @brendandburns sorry for the delay in getting back to this.

I actually think it might be simpler if we just try and create the ApiClient and if that fails we fall back to creating one that points to localhost.  Let me know what you think.

**Comment by ryanjbaxter** [comment]
@yue9944882 I believe I fixed the formatting issues, sorry about that

**Review by yue9944882 — COMMENTED** [review]
/lgtm
/approve

@ryanjbaxter thanks a bunch!
